### PR TITLE
Fix zod key detection with ZodDefault and ZodDiscriminatedUnion

### LINKED ISSUE #73: Issue with mixed naming and zod defaults
### Describe the bug

When trying to use a zod schema with defaults, neato/conf cannot parse with mixed naming conventions.

### Which package/app is affected (leave empty if unsure)

@neato/config

### Link to the code that reproduces this issue

_No response_

### Steps to reproduce

running this test will currently fail. But if you remove the top level zod default it works again.

```
test('mixed naming convention, valid', () => {
    setEnv({
      CONF_PASCAL__PASCAL_CASE: 'test_pascal',
      CONF_SNAKE__SNAKE_CASE: 'test_snake',
    });
    const schema = z.object({
      Pascal: z.object({
        PascalCase: z.string().default('default_pascal'),
      }),
      snake: z.object({
        snake_case: z.string().default('default_snake'),
      }).default({}),
    });
    const config = createConfigLoader({ assert: 'throw' })
      .addFromEnvironment('CONF_')
      .addZodSchema(schema)
      .load();
    expect(config).toStrictEqual({
      Pascal:{ PascalCase: 'test_pascal'},
      snake:{ snake_case: 'test_snake'}
    });
  });
```

### Expected Behavior

I expected this to work

### Extra details

_No response_

### PR DESCRIPTION
**Pull request by mrjvs**
changes:
- Add special cases for ZodDefault and ZodDiscriminatedUnion in key extraction

This resolves #73

### CODE REVIEW

File: packages/config/src/schemas/zod.ts [hunk 1]
```diff
@@ -1,27 +1,50 @@
...
-  });
-  return out;
+    return newKeys.flat();
+  }
+
+  if (def.typeName === ZodFirstPartyTypeKind.ZodDiscriminatedUnion) {
+    const newKeys = def.options.map((objType) =>
+      recursiveSearchForKeys(objType._def, path),
+    );
+    return newKeys.flat();
```
Comment (binaryoverload) [inline packages/config/src/schemas/zod.ts:35]: Maybe use flatMap here to be clearer about your intention?

File: packages/config/src/schemas/zod.ts [hunk 2]
```diff
@@ -1,27 +1,50 @@
...
-      outputKey: keyArray.join('__'),
+  if (def.typeName === ZodFirstPartyTypeKind.ZodObject) {
+    const shape = def.shape();
+    const entries = Object.entries(shape);
+    const newKeys = entries.map(([k, v]) => {
+      return recursiveSearchForKeys(v._def, [...path, k]);
     });
-  });
-  return out;
+    return newKeys.flat();
```
Comment (binaryoverload) [inline packages/config/src/schemas/zod.ts:28]: See flatMap comment

**Review by binaryoverload — CHANGES_REQUESTED** [review]

**Review by binaryoverload — APPROVED** [review]
